# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='service.proto',
  package='grpcSpeech',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\rservice.proto\x12\ngrpcSpeech\" \n\rSpeechRequest\x12\x0f\n\x07Message\x18\x01 \x01(\t\"\x1c\n\rSkillResponse\x12\x0b\n\x03URL\x18\x01 \x01(\t\"k\n\x0eSpeechResponse\x12\x10\n\x08\x44uration\x18\x01 \x01(\x02\x12\x0f\n\x07Message\x18\x02 \x01(\t\x12\x12\n\nGraphicURL\x18\x03 \x01(\t\x12\x13\n\x0bGraphicType\x18\x04 \x01(\x05\x12\r\n\x05\x45rror\x18\x05 \x01(\t2\xa2\x01\n\ngrpcSpeech\x12J\n\x0f\x44\x65termineSpeech\x12\x19.grpcSpeech.SpeechRequest\x1a\x1a.grpcSpeech.SpeechResponse\"\x00\x12H\n\x0e\x44\x65termineSkill\x12\x19.grpcSpeech.SpeechRequest\x1a\x19.grpcSpeech.SkillResponse\"\x00\x62\x06proto3'
)




_SPEECHREQUEST = _descriptor.Descriptor(
  name='SpeechRequest',
  full_name='grpcSpeech.SpeechRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Message', full_name='grpcSpeech.SpeechRequest.Message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=61,
)


_SKILLRESPONSE = _descriptor.Descriptor(
  name='SkillResponse',
  full_name='grpcSpeech.SkillResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='URL', full_name='grpcSpeech.SkillResponse.URL', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=63,
  serialized_end=91,
)


_SPEECHRESPONSE = _descriptor.Descriptor(
  name='SpeechResponse',
  full_name='grpcSpeech.SpeechResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Duration', full_name='grpcSpeech.SpeechResponse.Duration', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Message', full_name='grpcSpeech.SpeechResponse.Message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='GraphicURL', full_name='grpcSpeech.SpeechResponse.GraphicURL', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='GraphicType', full_name='grpcSpeech.SpeechResponse.GraphicType', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Error', full_name='grpcSpeech.SpeechResponse.Error', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=93,
  serialized_end=200,
)

DESCRIPTOR.message_types_by_name['SpeechRequest'] = _SPEECHREQUEST
DESCRIPTOR.message_types_by_name['SkillResponse'] = _SKILLRESPONSE
DESCRIPTOR.message_types_by_name['SpeechResponse'] = _SPEECHRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SpeechRequest = _reflection.GeneratedProtocolMessageType('SpeechRequest', (_message.Message,), {
  'DESCRIPTOR' : _SPEECHREQUEST,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:grpcSpeech.SpeechRequest)
  })
_sym_db.RegisterMessage(SpeechRequest)

SkillResponse = _reflection.GeneratedProtocolMessageType('SkillResponse', (_message.Message,), {
  'DESCRIPTOR' : _SKILLRESPONSE,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:grpcSpeech.SkillResponse)
  })
_sym_db.RegisterMessage(SkillResponse)

SpeechResponse = _reflection.GeneratedProtocolMessageType('SpeechResponse', (_message.Message,), {
  'DESCRIPTOR' : _SPEECHRESPONSE,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:grpcSpeech.SpeechResponse)
  })
_sym_db.RegisterMessage(SpeechResponse)



_GRPCSPEECH = _descriptor.ServiceDescriptor(
  name='grpcSpeech',
  full_name='grpcSpeech.grpcSpeech',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=203,
  serialized_end=365,
  methods=[
  _descriptor.MethodDescriptor(
    name='DetermineSpeech',
    full_name='grpcSpeech.grpcSpeech.DetermineSpeech',
    index=0,
    containing_service=None,
    input_type=_SPEECHREQUEST,
    output_type=_SPEECHRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='DetermineSkill',
    full_name='grpcSpeech.grpcSpeech.DetermineSkill',
    index=1,
    containing_service=None,
    input_type=_SPEECHREQUEST,
    output_type=_SKILLRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_GRPCSPEECH)

DESCRIPTOR.services_by_name['grpcSpeech'] = _GRPCSPEECH

# @@protoc_insertion_point(module_scope)
